CREATE TABLE AL94375295.ACOMPAÑANTES_VISITA (
	CONS_ACOMPAÑAMIENTO NUMBER(10) NOT NULL,
	CONS_VISITA NUMBER(10) NOT NULL,
	NOMBRES VARCHAR2(25) NOT NULL,
	APELLIDOS VARCHAR2(25) NOT NULL,
	PRIMARY KEY (CONS_ACOMPAÑAMIENTO)
);

CREATE TABLE AL94375295.AFILIACIONES (
	NRO_AFILIACION NUMBER(8) NOT NULL,
	NOMBRE VARCHAR2(50) NOT NULL,
	IDENTIFICACION NUMBER(12) NOT NULL,
	TELEFONO VARCHAR2(10),
	CIUDAD NUMBER(8) NOT NULL,
	FECHA_AFILIACIÓN DATE NOT NULL,
	PRIMARY KEY (NRO_AFILIACION)
);

CREATE TABLE AL94375295.CIUDADES (
	COD_CIUDAD NUMBER(8) NOT NULL,
	NOMBRE VARCHAR2(30) NOT NULL,
	ACTIVA NUMBER(1) NOT NULL,
	PRIMARY KEY (COD_CIUDAD)
);

CREATE TABLE AL94375295.CONSUMOS (
	CONSECUTIVO NUMBER(6) NOT NULL,
	CONS_VISITA NUMBER(10) NOT NULL,
	COD_PRODUCTO NUMBER(5) NOT NULL,
	CANTIDAD NUMBER(4,2) NOT NULL,
	OBSERVACION VARCHAR2(50),
	PRIMARY KEY (CONSECUTIVO)
);

CREATE TABLE AL94375295.DEPORTES (
	CODIGO NUMBER(3) NOT NULL,
	NOMBRE VARCHAR2(50) NOT NULL,
	PRIMARY KEY (CODIGO)
);

CREATE TABLE AL94375295.DEPORTES_SOCIOS (
	CONSECUTIVO NUMBER(6) NOT NULL,
	ID_SOCIO NUMBER(8) NOT NULL,
	COD_DEPORTE NUMBER(3) NOT NULL,
	PRIMARY KEY (CONSECUTIVO)
);

CREATE TABLE AL94375295.PRODUCTOS (
	CODIGO NUMBER(5) NOT NULL,
	TIPO NUMBER(2) NOT NULL,
	NOMBRE VARCHAR2(50) NOT NULL,
	PRECIO NUMBER(8,2) NOT NULL,
	PRIMARY KEY (CODIGO)
);

CREATE TABLE AL94375295.SOCIOS (
	IDENTIFICACIÓN NUMBER(8) NOT NULL,
	NRO_AFILIACION NUMBER(8) NOT NULL,
	CEDULA NUMBER(12) NOT NULL,
	NOMBRES VARCHAR2(30) NOT NULL,
	APELLIDOS VARCHAR2(30) NOT NULL,
	TELEFONO NUMBER(10),
	EMPRESA VARCHAR2(30),
	AFICIONES VARCHAR2(200),
	FECHA_AFILIACIÓN DATE NOT NULL,
	PRIMARY KEY (IDENTIFICACIÓN)
);

CREATE TABLE AL94375295.TIPOS_PRODUCTO (
	CODIGO NUMBER(2) NOT NULL,
	NOMBRE VARCHAR2(10) NOT NULL,
	PRIMARY KEY (CODIGO)
);

CREATE TABLE AL94375295.VISITAS (
	CONS_VISITA NUMBER(10) NOT NULL,
	ID_SOCIO NUMBER(8) NOT NULL,
	FECHA_HORA_INGRESO TIMESTAMP(6)(0) NOT NULL,
	FECHA_HORA_SALIDA TIMESTAMP(6)(0),
	CANTIDAD_ACOMPAÑANTES NUMBER(2),
	PRIMARY KEY (CONS_VISITA)
);

ALTER TABLE AL94375295.ACOMPAÑANTES_VISITA
	ADD FOREIGN KEY (CONS_VISITA) 
	REFERENCES VISITAS (CONS_VISITA);



ALTER TABLE AL94375295.AFILIACIONES
	ADD FOREIGN KEY (CIUDAD) 
	REFERENCES CIUDADES (COD_CIUDAD);



ALTER TABLE AL94375295.CONSUMOS
	ADD FOREIGN KEY (CONS_VISITA) 
	REFERENCES VISITAS (CONS_VISITA);

ALTER TABLE AL94375295.CONSUMOS
	ADD FOREIGN KEY (COD_PRODUCTO) 
	REFERENCES PRODUCTOS (CODIGO);



ALTER TABLE AL94375295.DEPORTES_SOCIOS
	ADD FOREIGN KEY (ID_SOCIO) 
	REFERENCES SOCIOS (IDENTIFICACIÓN);

ALTER TABLE AL94375295.DEPORTES_SOCIOS
	ADD FOREIGN KEY (COD_DEPORTE) 
	REFERENCES DEPORTES (CODIGO);



ALTER TABLE AL94375295.PRODUCTOS
	ADD FOREIGN KEY (TIPO) 
	REFERENCES TIPOS_PRODUCTO (CODIGO);



ALTER TABLE AL94375295.SOCIOS
	ADD FOREIGN KEY (NRO_AFILIACION) 
	REFERENCES AFILIACIONES (NRO_AFILIACION);



ALTER TABLE AL94375295.VISITAS
	ADD FOREIGN KEY (ID_SOCIO) 
	REFERENCES SOCIOS (IDENTIFICACIÓN);



CREATE UNIQUE INDEX AL94375295.SYS_C006989 ON AL94375295.CIUDADES (COD_CIUDAD);

CREATE UNIQUE INDEX AL94375295.SYS_C006999 ON AL94375295.AFILIACIONES (NRO_AFILIACION);

CREATE UNIQUE INDEX AL94375295.SYS_C007014 ON AL94375295.SOCIOS (IDENTIFICACIÓN);

CREATE UNIQUE INDEX AL94375295.SYS_C007021 ON AL94375295.VISITAS (CONS_VISITA);

CREATE UNIQUE INDEX AL94375295.SYS_C007027 ON AL94375295.ACOMPAÑANTES_VISITA (CONS_ACOMPAÑAMIENTO);

CREATE UNIQUE INDEX AL94375295.SYS_C007031 ON AL94375295.TIPOS_PRODUCTO (CODIGO);

CREATE UNIQUE INDEX AL94375295.SYS_C007036 ON AL94375295.PRODUCTOS (CODIGO);

CREATE UNIQUE INDEX AL94375295.SYS_C007042 ON AL94375295.CONSUMOS (CONSECUTIVO);

CREATE UNIQUE INDEX AL94375295.SYS_C007047 ON AL94375295.DEPORTES (CODIGO);

CREATE UNIQUE INDEX AL94375295.SYS_C007051 ON AL94375295.DEPORTES_SOCIOS (CONSECUTIVO);

CREATE OR REPLACE TRIGGER acompañantes_visita_fire
BEFORE INSERT ON acompañantes_visita
FOR EACH ROW
BEGIN
  SELECT acompañantes_visita_seq.NEXTVAL
  INTO   :new.cons_acompañamiento
  FROM   dual;
END;

CREATE OR REPLACE TRIGGER afiliacion_fire
BEFORE INSERT ON afiliaciones
FOR EACH ROW
BEGIN
  SELECT afiliacion_seq.NEXTVAL
  INTO   :new.nro_afiliacion
  FROM   dual;
END;

CREATE OR REPLACE TRIGGER ciudad_fire
BEFORE INSERT ON ciudades
FOR EACH ROW
BEGIN
  SELECT ciudad_seq.NEXTVAL
  INTO   :new.cod_Ciudad
  FROM   dual;
END;

CREATE OR REPLACE TRIGGER consumo_fire
BEFORE INSERT ON consumos
FOR EACH ROW
BEGIN
  SELECT consumo_seq.NEXTVAL
  INTO   :new.consecutivo
  FROM   dual;
END;

CREATE OR REPLACE TRIGGER deportes_socio_fire
BEFORE INSERT ON deportes_socios
FOR EACH ROW
BEGIN
  SELECT deportes_socio_seq.NEXTVAL
  INTO   :new.consecutivo
  FROM   dual;
END;

CREATE OR REPLACE TRIGGER visita_fire
BEFORE INSERT ON visitas
FOR EACH ROW
BEGIN
  SELECT visita_seq.NEXTVAL
  INTO   :new.cons_visita
  FROM   dual;
END;

